name: CI/CD with nerdctl and Docker Hub for flask app DJ1

on:
  push:
    branches: [ master ]

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | nerdctl login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push image with nerdctl
      run: |
        sudo /usr/local/bin/nerdctl build -t docker.io/jaymaverick/flask-expense-app:${{ github.sha }} .
        sudo /usr/local/bin/nerdctl push docker.io/jaymaverick/flask-expense-app:${{ github.sha }}

    - name: Trigger Kubernetes rollout
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        /usr/bin/kubectl set image deployment/flask-expense-deployment flask-expense-app=docker.io/jaymaverick/flask-expense-app:${{ github.sha }} -n app
